import "~/styles/globals.css";

import {TRPCReactProvider} from "~/trpc/react";

import {Inter as FontSans} from "next/font/google"

import {cn} from "~/lib/utils"
import AdminSidebar from '~/components/admin/layout/AdminSidebar';
import Header from '~/components/admin/layout/AdminHeader';
import {ClerkProvider} from '@clerk/nextjs';
import useTranslation from 'next-translate/useTranslation';

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    const {lang} = useTranslation('common')

    return <ClerkProvider>
        <html lang={lang}>
        <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
        )}>
        <TRPCReactProvider>
            <Header/>
            <div className="flex h-screen overflow-hidden">
                <AdminSidebar/>
                <main className="w-full pt-16">{children}</main>
            </div>
        </TRPCReactProvider>
        </body>
        </html>
    </ClerkProvider>
}
